cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

reviews/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.reviews, name='reviews'),
    path('add/', views.add_review, name='add_review'),
]

tv_shack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('search/', include('search.urls')),
    path('reviews/', include('reviews.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
from django.db import models


class Review(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

reviews/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('name', 'email', 'body')

reviews/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from .models import Review
from .forms import ReviewForm


def reviews(request):
    if request.method == 'POST':
        review = ReviewForm(request.POST)
        if review.is_valid():
            review.save()
            messages.info(request, 'Your review has been submitted.')
            reviews = Review.objects.all()
            return render(request, 'reviews/reviews.html', {'reviews': reviews})
    else:
        reviews = Review.objects.all()
        context = {
            'reviews': reviews,
        }
    return render(request, 'reviews/reviews.html', context)


def add_review(request):
    """ A view to display form for adding new reviews """
    if request.method == 'POST':
        review = ReviewForm(request.POST)
        if review.is_valid():
            review.save()
            messages.info(request, 'Your review has been submitted.')
            reviews = Review.objects.all()
            return render(request, 'reviews/reviews.html', {'reviews': reviews})
    else:
        reviews = Review.objects.all()
        context = {
            'reviews': reviews,
        }
    return render(request, 'reviews/add_review.html', context)

reviews/templates/reviews/add_review.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<!-- Title -->
<h1 class="text-center title">Reviews</h1>
<!-- Reviews Display -->
<div class="container mt-5">

<!-- Adding Review -->
   {% if user.is_authenticated %}
   <div class="row mt-5">
      <div class="col-md-6">
         <div class="bg-black rounded p-3 px-3 mb-3 text-uppercase"><strong>Add A Review</strong>
         </div>
      </div>
   </div>
   <form action="{% url 'add_review' %}" method="POST">
      {% csrf_token %}
      <div class="row">
         <div class="col-md-6 mb-3"><label for="id_name">Name:</label>
            <input type="text" class="form-control" name="name" maxlength="80" required id="id_name">
         </div>
      </div>
      <div class="row">
         <div class="col-md-6 mb-3"><label for="id_email">Email:</label>
            <input type="email"  class="form-control" name="email" maxlength="254" required id="id_email">
         </div>
      </div>
      <div class="row">
         <div class="col-md-6 mb-3"><label for="id_body">Review:</label>
            <textarea name="body"  class="form-control" cols="40" rows="10" required id="id_body"></textarea>
         </div>
      </div>
      <button class="btn btn-dark rounded-pill py-2 mb-4 review-form" type="submit">Add Review</button>
   </form>
{% endif %}
</div>
{% endblock %}

reviews/templates/reviews/reviews.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<!-- Title -->
<h1 class="text-center title standard-text">Reviews</h1>
<!-- Reviews Display -->
<div class="container mt-5">
   <div class="row">
      <div class="col-md-12">
         <div class="bg-black rounded p-3 px-3 mb-3 text-uppercase standard-text"><strong>Site Reviews</strong>
         </div>
      </div>
   </div>
   {% for review in reviews %}
   <ul class="list-group mb-4">
      <li class="list-group-item">
         <div class="row">
            <div class="col-6 mb-1 text-capitalize">
               <h6 class=""><strong>Reviewer:</strong> {{ review.name }}</h6>
            </div>
            <div class="col-6">
               <h6 class="text-right"><strong>Review Date:</strong> {{ review.created_on }}</h6>
            </div>
         </div>
         <div class="row">
            <div class="col-12">
               <p class="lh-condensed text-muted"></p>
               {{ review.body }}
            </div>
         </div>
      </li>
   </ul>
   {% endfor %}
   <div class="row">
      <div class="col-12 text-center">
         <a href="{% url 'add_review' %}"><p class="rounded-pill button-tag">Add Review</p></a>
      </div>
   </div>

</div>
{% endblock %}